### ISSUE TITLE
Add possibility to specify conf for remote adapters

### ISSUE THREAD

**Issue by peel** [snowplow/beam-enrich#24]
Remote adapters require some configuration, for example : 
```
remoteAdapters = [
￼	   {
￼	       vendor: "special-vendor"
￼	       version: "v1"
￼	       url: "http://remote-adapter.com:9090"
￼	       connectionTimeout: 1000
￼	       readTimeout: 5000
￼	   }
￼]
```
Currently there is no way to pass this configuration to `beam-enrich`, as it only accepts command-line arguments.

A solution could be to add an optional argument containing the path to the configuration file with the remote adapters.

Moved from: https://github.com/snowplow/snowplow/issues/4080

**Comment by alexanderdean** [comment]
This all feels a bit non-standard. If Snowplow supports N remote adapters, maybe we should come up with a new self-describing JSON format for them, like enrichments.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/271
