### ISSUE TITLE
Volume mount permissions in containers

### ISSUE THREAD

**Issue by peel** [snowplow/beam-enrich#27]
Currently Snowplow containers run as snowplow user. 

When mounting a volume, it gets mounted as root, this makes impossible to access files from the program that is running as snowplow user.

The use case for this was on a gcp container, we tried to pass the service account file to the container using a volume, so the program running there could do the authentication and connect to gcp.

Example: 
```
docker run --rm -v /root:/cfg -e GOOGLE_APPLICATION_CREDENTIALS='/cfg/sp-loader.json' snowplow-docker-registry.bintray.io/snowplow/snowplow-bigquery-mutator:0.1.0-rc13 listen --resolver=$RESOLVER --config=$CONFIG --verbose
```

This seems to be an old issue yet to have a proper solution https://github.com/moby/moby/issues/2259

Moved from: https://github.com/snowplow/snowplow/issues/3896

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/274
