### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by simplylizz** [snowplow/beam-enrich#35]
Hey,

I'm just trying to setup enricher, so I tried to follow your instructions and noticed a few issues:
1. A version in the example is 0.1.0 which is quite old.
2. In the docs you use bintray's registry, but the most recent stable version there is `0.3.0` while on the docker hub it's `1.1.0`. So perhaps it's worth changing docs to use an image from the docker hub?

**Comment by chuwy** [comment]
Thanks @simplylizz! @oguzhanunlu could you please move documentation to docs.snowplowanalytics.com/ and update it please.

**Comment by oguzhanunlu** [comment]
Sure @chuwy

**Comment by oguzhanunlu** [comment]
Documentation is updated at https://docs.snowplowanalytics.com/docs/setup-snowplow-on-gcp/setup-validation-and-enrich-beam-enrich/ and 1.2.0 release will also update README here, thanks for the heads up, @simplylizz !
